{
  "cryptography":[
      {
         "reason_to_ignore": "Temporarily ignoring to fix CRITICALs",
         "description":"Issue summary: Generating excessively long X9.42 DH keys or checking\nexcessively long X9.42 DH keys or parameters may be very slow.\n\nImpact summary: Applications that use the functions DH_generate_key() to\ngenerate an X9.42 DH key may experience long delays.  Likewise, applications\nthat use DH_check_pub_key(), DH_check_pub_key_ex() or EVP_PKEY_public_check()\nto check an X9.42 DH key or X9.42 DH parameters may experience long delays.\nWhere the key or parameters that are being checked have been obtained from\nan untrusted source this may lead to a Denial of Service.\n\nWhile DH_check() performs all the necessary checks (as of CVE-2023-3817),\nDH_check_pub_key() doesn't make any of these checks, and is therefore\nvulnerable for excessively large P and Q parameters.\n\nLikewise, while DH_generate_key() performs a check for an excessively large\nP, it doesn't check for an excessively large Q.\n\nAn application that calls DH_generate_key() or DH_check_pub_key() and\nsupplies a key or parameters obtained from an untrusted sour",
         "vulnerability_id":"CVE-2023-5678",
         "name":"CVE-2023-5678",
         "package_name":"cryptography",
         "package_details":{
            "file_path":"opt/conda/lib/python3.9/site-packages/cryptography-41.0.5.dist-info/METADATA",
            "name":"cryptography",
            "package_manager":"PYTHONPKG",
            "version":"41.0.5",
            "release":null
         },
         "remediation":{
            "recommendation":{
               "text":"None Provided"
            }
         },
         "cvss_v3_score":7.5,
         "cvss_v30_score":0.0,
         "cvss_v31_score":7.5,
         "cvss_v2_score":0.0,
         "cvss_v3_severity":"HIGH",
         "source_url":"https://nvd.nist.gov/vuln/detail/CVE-2023-5678",
         "source":"NVD",
         "severity":"HIGH",
         "status":"ACTIVE",
         "title":"CVE-2023-5678 - cryptography"
      }
  ],
  "transformers": [
    {
      "reason_to_ignore": "Need guidance from HF team on how to upgrade as it's breaking the image. Temporarily ignoring to patch other CVEs.",
      "description": "\n Insecure Temporary File in GitHub repository huggingface/transformers prior to 4.30.0..",
      "vulnerability_id": "CVE-2023-2800",
      "name": "CVE-2023-2800",
      "package_name": "transformers",
      "package_details": {
        "file_path": null,
        "name": "transformers",
        "package_manager": "PYTHONPKG",
        "version": "4.26.0",
        "release": ""
      },
      "remediation": {
        "recommendation": {
          "text": "Update transformers to 4.30.0."
        }
      },
      "cvss_v3_score": 4.7,
      "cvss_v30_score": 4.7,
      "cvss_v31_score": 4.7,
      "cvss_v2_score": 4.7,
      "cvss_v3_severity": "MEDIUM",
      "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2023-2800",
      "source": "NVD",
      "severity": "MEDIUM",
      "status": "ACTIVE",
      "title": "CVE-2023-2800 - transformers"
    }
  ],
  "libzmq5": [
    {
      "reason_to_ignore": "The current version is marked as a fix version in the CVE notes, and this is the latest version.",
      "description": "\n It was discovered that ZeroMQ incorrectly handled certain application metadata.\n A remote attacker could use this issue to cause ZeroMQ to crash, or possibly\n execute arbitrary code.",
      "vulnerability_id": "CVE-2019-13132",
      "name": "CVE-2019-13132",
      "package_name": "libzmq5",
      "package_details": {
        "file_path": null,
        "name": "libzmq5",
        "package_manager": "OS",
        "version": "4.3.2",
        "release": "2ubuntu1"
      },
      "remediation": {
        "recommendation": {
          "text": "None Provided"
        }
      },
      "cvss_v3_score": 9.8,
      "cvss_v30_score": 0,
      "cvss_v31_score": 9.8,
      "cvss_v2_score": 7.5,
      "cvss_v3_severity": "CRITICAL",
      "source_url": "https://people.canonical.com/~ubuntu-security/cve/2019/CVE-2019-13132.html",
      "source": "UBUNTU_CVE",
      "severity": "HIGH",
      "status": "ACTIVE",
      "title": "CVE-2019-13132 - libzmq5"
    }
  ],
  "rdflib": [
    {
      "reason_to_ignore": "This is the latest version of the package.",
      "description": "## Overview\n[rdflib](https://pypi.org/project/rdflib/) is a Python library for working with RDF, a simple yet powerful language for representing information.\nAffected versions of this package are vulnerable to Server-Side Request Forgery (SSRF). `rdflib` provides no way to control how external references are resolved, nor a way to implement caching of external resources.\r\n\r\nIf a web service takes `POST`ed `JSON-LD` data, `rdflib` will attempt to resolve any URL in the `@context`.\r\nThis can lead to:\r\n1. attackers being able to probe internal networks, by having `rdflib` request potential non-public URLs\r\n2. reflection attacks, if the same or slightly-different URLs are repeated multiple times in the `@context`\r\n3. resource exhaustion, as the entire remote file is loaded into memory before JSON parsing is attempted\r\n4. Denial of Service, if web or task workers are tied up waiting for extended periods for HTTP requests to complete\r\n5. attackers being able to probe the local filesystem using `file://` URLs\n## Rem",
      "vulnerability_id": "SNYK-PYTHON-RDFLIB-1324490",
      "name": "SNYK-PYTHON-RDFLIB-1324490",
      "package_name": "rdflib",
      "package_details": {
        "file_path": "opt/conda/lib/python3.9/site-packages/rdflib-6.3.1.dist-info/METADATA",
        "name": "rdflib",
        "package_manager": "PYTHONPKG",
        "version": "6.3.1",
        "release": null
      },
      "remediation": {
        "recommendation": {
          "text": "None Provided"
        }
      },
      "cvss_v3_score": 8.6,
      "cvss_v30_score": 0,
      "cvss_v31_score": 8.6,
      "cvss_v2_score": 0,
      "cvss_v3_severity": "HIGH",
      "source_url": "https://security.snyk.io/vuln/SNYK-PYTHON-RDFLIB-1324490",
      "source": "SNYK",
      "severity": "HIGH",
      "status": "ACTIVE",
      "title": "IN1-PYTHON-RDFLIB-1324490 - rdflib"
    }
  ]
}
