{
  "torch": [
    {
      "description": "PyTorch is a Python package that provides tensor computation with strong GPU acceleration and deep neural networks built on a tape-based autograd system. In version 2.5.1 and prior, a Remote Command Execution (RCE) vulnerability exists in PyTorch when loading a model using torch.load with weights_only=True. This issue has been patched in version 2.6.0.",
      "vulnerability_id": "CVE-2025-32434",
      "name": "CVE-2025-32434",
      "package_name": "torch",
      "package_details": {
        "file_path": "/opt/conda/lib/python3.11/site-packages/torch-2.4.0+cpu.dist-info/METADATA",
        "name": "torch",
        "package_manager": "PYTHON",
        "version": "2.4.0+cpu",
        "release": null
      },
      "remediation": {
        "recommendation": {
          "text": "None Provided"
        }
      },
      "cvss_v3_score": 0.0,
      "cvss_v30_score": 0.0,
      "cvss_v31_score": 0.0,
      "cvss_v2_score": 0.0,
      "cvss_v3_severity": "CRITICAL",
      "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2025-32434",
      "source": "NVD",
      "severity": "CRITICAL",
      "status": "ACTIVE",
      "title": "CVE-2025-32434 - torch",
      "reason_to_ignore": "this container is specifically pytorch 2.5.x so we canâ€™t upgrade to 2.6"
    }
  ],
  "libxml2": [
    {
      "description": "In libxml2 before 2.13.8 and 2.14.x before 2.14.2, xmlSchemaIDCFillNodeTables in xmlschemas.c has a heap-based buffer under-read. To exploit this, a crafted XML document must be validated against an XML schema with certain identity constraints, or a crafted XML schema must be used.",
      "vulnerability_id": "CVE-2025-32415",
      "name": "CVE-2025-32415",
      "package_name": "libxml2",
      "package_details": {
        "file_path": null,
        "name": "libxml2",
        "package_manager": "OS",
        "version": "2.9.13+dfsg",
        "release": "1ubuntu0.6"
      },
      "remediation": {
        "recommendation": {
          "text": "None Provided"
        }
      },
      "cvss_v3_score": 7.5,
      "cvss_v30_score": 0.0,
      "cvss_v31_score": 7.5,
      "cvss_v2_score": 0.0,
      "cvss_v3_severity": "HIGH",
      "source_url": "https://people.canonical.com/~ubuntu-security/cve/2025/CVE-2025-32415.html",
      "source": "UBUNTU_CVE",
      "severity": "HIGH",
      "status": "ACTIVE",
      "title": "CVE-2025-32415 - libxml2",
      "reason_to_ignore": "N/A"
    },
    {
      "description": "In libxml2 before 2.13.8 and 2.14.x before 2.14.2, out-of-bounds memory access can occur in the Python API (Python bindings) because of an incorrect return value. This occurs in xmlPythonFileRead and xmlPythonFileReadRaw because of a difference between bytes and characters.",
      "vulnerability_id": "CVE-2025-32414",
      "name": "CVE-2025-32414",
      "package_name": "libxml2",
      "package_details": {
        "file_path": null,
        "name": "libxml2",
        "package_manager": "OS",
        "version": "2.9.13+dfsg",
        "release": "1ubuntu0.6"
      },
      "remediation": {
        "recommendation": {
          "text": "None Provided"
        }
      },
      "cvss_v3_score": 7.5,
      "cvss_v30_score": 0.0,
      "cvss_v31_score": 7.5,
      "cvss_v2_score": 0.0,
      "cvss_v3_severity": "HIGH",
      "source_url": "https://people.canonical.com/~ubuntu-security/cve/2025/CVE-2025-32414.html",
      "source": "UBUNTU_CVE",
      "severity": "HIGH",
      "status": "ACTIVE",
      "title": "CVE-2025-32414 - libxml2",
      "reason_to_ignore": "N/A"
    }
  ]
}
