{
    "rdflib": [
        {
            "description": "[rdflib](https://pypi.org/project/rdflib/) is a Python library for working with RDF, a simple yet powerful language for representing information.\n\nAffected versions of this package are vulnerable to Server-Side Request Forgery (SSRF). `rdflib` provides no way to control how external references are resolved, nor a way to implement caching of external resources.\r\n\r\nIf a web service takes `POST`ed `JSON-LD` data, `rdflib` will attempt to resolve any URL in the `@context`.\r\nThis can lead to:\r\n1. attackers being able to probe internal networks, by having `rdflib` request potential non-public URLs\r\n2. reflection attacks, if the same or slightly-different URLs are repeated multiple times in the `@context`\r\n3. resource exhaustion, as the entire remote file is loaded into memory before JSON parsing is attempted\r\n4. Denial of Service, if web or task workers are tied up waiting for extended periods for HTTP requests to complete\r\n5. attackers being able to probe the local filesystem using `file://` URLs",
            "vulnerability_id": "IN1-PYTHON-RDFLIB-1324490",
            "name": "IN1-PYTHON-RDFLIB-1324490",
            "package_name": "rdflib",
            "package_details": {
                "file_path": "opt/conda/lib/python3.8/site-packages/rdflib-6.2.0.dist-info/METADATA",
                "name": "rdflib",
                "package_manager": "PYTHONPKG",
                "version": "6.2.0",
                "release": null
            },
            "remediation": {
                "recommendation": {
                    "text": "None Provided"
                }
            },
            "cvss_v3_score": 8.6,
            "cvss_v30_score": 0.0,
            "cvss_v31_score": 8.6,
            "cvss_v2_score": 0.0,
            "cvss_v3_severity": "HIGH",
            "source_url": "https://snyk.io/vuln/SNYK-PYTHON-RDFLIB-1324490",
            "source": "SNYK",
            "severity": "HIGH",
            "status": "ACTIVE",
            "title": "SNYK-PYTHON-RDFLIB-1324490 - rdflib",
            "reason_to_ignore": "Latest version of rdflib is being installed"
        },
        {
            "description": "[rdflib](https://pypi.org/project/rdflib/) is a Python library for working with RDF, a simple yet powerful language for representing information.\n\nAffected versions of this package are vulnerable to Server-Side Request Forgery (SSRF). `rdflib` provides no way to control how external references are resolved, nor a way to implement caching of external resources.\r\n\r\nIf a web service takes `POST`ed `JSON-LD` data, `rdflib` will attempt to resolve any URL in the `@context`.\r\nThis can lead to:\r\n1. attackers being able to probe internal networks, by having `rdflib` request potential non-public URLs\r\n2. reflection attacks, if the same or slightly-different URLs are repeated multiple times in the `@context`\r\n3. resource exhaustion, as the entire remote file is loaded into memory before JSON parsing is attempted\r\n4. Denial of Service, if web or task workers are tied up waiting for extended periods for HTTP requests to complete\r\n5. attackers being able to probe the local filesystem using `file://` URLs",
            "vulnerability_id": "SNYK-PYTHON-RDFLIB-1324490",
            "name": "SNYK-PYTHON-RDFLIB-1324490",
            "package_name": "rdflib",
            "package_details": {
                "file_path": "opt/conda/lib/python3.8/site-packages/rdflib-6.2.0.dist-info/METADATA",
                "name": "rdflib",
                "package_manager": "PYTHONPKG",
                "version": "6.2.0",
                "release": null
            },
            "remediation": {
                "recommendation": {
                    "text": "None Provided"
                }
            },
            "cvss_v3_score": 8.6,
            "cvss_v30_score": 0.0,
            "cvss_v31_score": 8.6,
            "cvss_v2_score": 0.0,
            "cvss_v3_severity": "HIGH",
            "source_url": "https://snyk.io/vuln/SNYK-PYTHON-RDFLIB-1324490",
            "source": "SNYK",
            "severity": "HIGH",
            "status": "ACTIVE",
            "title": "IN1-PYTHON-RDFLIB-1324490 - rdflib",
            "reason_to_ignore": "Latest version of rdflib is being installed"
        }
    ],
    "cryptography": [
        {
            "reason_to_ignore": "low severity",
            "description": " If an X.509 certificate contains a malformed policy constraint and policy processing is enabled, then a write lock will be taken twice recursively. On some operating systems (most widely: Windows) this results in a denial of service when the affected process hangs. Policy processing being enabled on a publicly facing server is not considered to be a common setup. Policy processing is enabled by passing the `-policy' argument to the command line utilities or by calling either `X509_VERIFY_PARAM_add0_policy()' or `X509_VERIFY_PARAM_set1_policies()' functions.",
            "vulnerability_id": "CVE-2022-3996",
            "name": "CVE-2022-3996",
            "package_name": "cryptography",
            "package_details": {
                "file_path": "opt/conda/lib/python3.8/site-packages/cryptography-39.0.0.dist-info/METADATA",
                "name": "cryptography",
                "package_manager": "PYTHONPKG",
                "version": "39.0.0",
                "release": null
            },
            "remediation": {
                "recommendation": {
                "text": "None Provided"
                }
            },
            "cvss_v3_score": 7.5,
            "cvss_v30_score": 0,
            "cvss_v31_score": 7.5,
            "cvss_v2_score": 0,
            "cvss_v3_severity": "HIGH",
            "source_url": "https://people.canonical.com/~ubuntu-security/cve/2022/CVE-2022-3996.html",
            "source": "UBUNTU_CVE",
            "severity": "LOW",
            "status": "ACTIVE",
            "title": "CVE-2022-3996 - cryptography"
        }
  ],
    "torch": [
        {
            "reason_to_ignore": "The binaries are patched for this CVE, but the system checks version and not code.",
            "description": " In PyTorch before trunk/89695, torch.jit.annotations.parse_type_line can cause arbitrary code execution because eval is used unsafely.",
            "vulnerability_id": "CVE-2022-45907",
            "name": "CVE-2022-45907",
            "package_name": "torch",
            "package_details": {
                "file_path": "opt/conda/lib/python3.8/site-packages/torch-1.11.0+cu113.dist-info/METADATA",
                "name": "torch",
                "package_manager": "PYTHONPKG",
                "version": "1.11.0+cu113",
                "release": null
            },
            "remediation": {
                "recommendation": {
                "text": "None Provided"
                }
            },
            "cvss_v3_score": 9.8,
            "cvss_v30_score": 0,
            "cvss_v31_score": 9.8,
            "cvss_v2_score": 0,
            "cvss_v3_severity": "CRITICAL",
            "source_url": "https://people.canonical.com/~ubuntu-security/cve/2022/CVE-2022-45907.html",
            "source": "UBUNTU_CVE",
            "severity": "MEDIUM",
            "status": "ACTIVE",
            "title": "CVE-2022-45907 - torch"
        },
        {
            "reason_to_ignore": "The binaries are patched for this CVE, but the system checks version and not code.",
            "description": "[torch](https://pypi.org/project/torch) is a Tensors and Dynamic neural networks in Python with strong GPU acceleration\n\nAffected versions of this package are vulnerable to Command Injection in `torch.jit.annotations.parse_type_line` which can cause arbitrary code execution because `eval` is used unsafely.",
            "vulnerability_id": "SNYK-PYTHON-TORCH-3149871",
            "name": "SNYK-PYTHON-TORCH-3149871",
            "package_name": "torch",
            "package_details": {
                "file_path": "opt/conda/lib/python3.8/site-packages/torch-1.11.0+cu113.dist-info/METADATA",
                "name": "torch",
                "package_manager": "PYTHONPKG",
                "version": "1.11.0+cu113",
                "release": null
            },
            "remediation": {
                "recommendation": {
                "text": "None Provided"
                }
            },
            "cvss_v3_score": 9.8,
            "cvss_v30_score": 0,
            "cvss_v31_score": 9.8,
            "cvss_v2_score": 0,
            "cvss_v3_severity": "CRITICAL",
            "source_url": "https://snyk.io/vuln/SNYK-PYTHON-TORCH-3149871",
            "source": "SNYK",
            "severity": "CRITICAL",
            "status": "ACTIVE",
            "title": "IN1-PYTHON-TORCH-3149871 - torch"
        }
  ]
}
