{
  "opencv-python": [
    {
      "description": "Heap buffer overflow in libwebp in Google Chrome prior to 116.0.5845.187 and libwebp 1.3.2 allowed a remote attacker to perform an out of bounds memory write via a crafted HTML page. (Chromium security severity: Critical)",
      "vulnerability_id": "CVE-2023-4863",
      "name": "CVE-2023-4863",
      "package_name": "opencv-python",
      "package_details": {
        "file_path": "opt/conda/lib/python3.10/site-packages/opencv_python-4.8.1.dist-info/METADATA",
        "name": "opencv-python",
        "package_manager": "PYTHONPKG",
        "version": "4.8.1",
        "release": null
      },
      "remediation": {
        "recommendation": {
          "text": "None Provided"
        }
      },
      "cvss_v3_score": 8.8,
      "cvss_v30_score": 0,
      "cvss_v31_score": 8.8,
      "cvss_v2_score": 0,
      "cvss_v3_severity": "HIGH",
      "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2023-4863",
      "source": "NVD",
      "severity": "HIGH",
      "status": "ACTIVE",
      "title": "CVE-2023-4863 - opencv-python"
    }
  ],
  "scipy": [
    {
      "description": "## Overview\n\nAffected versions of this package are vulnerable to Use After Free via the `Py_FindObjects()` function.\r\n\r\n**Note:**\r\n\r\nAccording to the maintainer, this issue is not to be considered a vulnerability.\n## PoC\n```\r\nvoid f() {\r\n  PyObject *result = PyList_New(1); // <-- new reference returned (line 878)\r\n  assert(result);\r\n  printf(\"%ld\\n\", result->ob_refcnt); // 1\r\n\r\n  PyErr_NoMemory(); // <-- error happens, an exception is thrown (line 890)\r\n  Py_XDECREF(result); // <-- destruction here (line 924)\r\n  printf(\"%ld\\n\", result->ob_refcnt); // 0\r\n\r\n  if (PyErr_Occurred()) {\r\n    Py_XDECREF(result); // <-- use after free here (line 931)\r\n    printf(\"%ld\\n\", result->ob_refcnt); // -1\r\n  }\r\n}\r\n```\n## Remediation\nUpgrade `scipy` to version 1.8.0 or higher.\n## References\n- [GitHub Commit](https://github.com/scipy/scipy/commit/e32fc2329d3dd23298725153c5b2cc7fcd0f14f1)\n- [GitHub Issue](https://github.com/scipy/scipy/issues/14713)\n- [GitHub PR](https://github.com/scipy/scipy/pull/15013)\n- [GitHub Release](http",
      "vulnerability_id": "SNYK-PYTHON-SCIPY-5759266",
      "name": "SNYK-PYTHON-SCIPY-5759266",
      "package_name": "scipy",
      "package_details": {
        "file_path": "opt/conda/lib/python3.10/site-packages/scipy-1.7.3.dist-info/METADATA",
        "name": "scipy",
        "package_manager": "PYTHONPKG",
        "version": "1.7.3",
        "release": null
      },
      "remediation": {
        "recommendation": {
          "text": "None Provided"
        }
      },
      "cvss_v3_score": 7.3,
      "cvss_v30_score": 0,
      "cvss_v31_score": 7.3,
      "cvss_v2_score": 0,
      "cvss_v3_severity": "HIGH",
      "source_url": "https://security.snyk.io/vuln/SNYK-PYTHON-SCIPY-5759266",
      "source": "SNYK",
      "severity": "HIGH",
      "status": "ACTIVE",
      "title": "IN1-PYTHON-SCIPY-5759266 - scipy"
    }
  ]
}
